sudo: required
services: 
  - docker

# run before executing test cases or deploy project
before_install:
  - docker build -t pawan2155/docker-react -f Dockerfile.dev . 

# series of commands to run our test suit 
script:
  - docker run -e CI=true pawan2155/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-056004397384"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"