sudo: required
services: 
  - docker

# run before executing test cases or deploy project
before_install:
  - docker build -t pawan2155/docker-react -f Dockerfile.dev . 

# series of commands to run our test suit 
script:
  - docker run -e CI=true pawan2155/docker-react npm run test